### ISSUE TITLE
Small problems

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qr-core#22]
https://landscape.io/github/qrefine/qr-core/4/messages/error

**Comment by zhengmin317** [comment]
@mpwaller 
The JClass is from jpyep;

>>from jpype import *                                                                                                     
>>print dir(JClass)
>>['__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__doc__', '__format__', '__get__', '__getattribute__', '__globals__', '__hash__', '__init__', '__module__', '__name__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'func_closure', 'func_code', 'func_defaults', 'func_dict', 'func_doc', 'func_globals', 'func_name']

**Comment by mpwaller** [comment]
is this also fixed??? but not closed?

**Comment by zhengmin317** [comment]
Each class/method is imported explicitly.
