### ISSUE TITLE
looks funny returning t, should be f, right?

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qr-core#23]
def target_and_gradients(self, x):
    self.update(x = x)
    tgx = self.x_target_functor(compute_gradients=True)
    f = tgx.target_work()
    g = tgx.gradients_wrt_atomic_parameters(u_iso=True)
    return t, g

**Comment by zhengmin317** [comment]
@mpwaller where is this code?

**Comment by mpwaller** [comment]
bottom of 
https://github.com/qrefine/qr-core/blob/master/calculator.py

**Comment by zhengmin317** [comment]
f should be t.
This is for b-factor refinement

**Comment by mpwaller** [comment]
ok I edit and close the issue
