### ISSUE TITLE
capping error

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qr-core#31]
The completion.py adds capping hydrogens, but removes oxygen atoms and changes the position of hydrogen connected with nitrogen. See the following before and after capping figures.
Before capping
![0](https://cloud.githubusercontent.com/assets/16145132/21499147/7e6b2144-cc33-11e6-87b3-a1078acb4a21.png)
After capping
![0_capping](https://cloud.githubusercontent.com/assets/16145132/21499148/81bf25ca-cc33-11e6-85f7-0f8cbc1c774a.png)

**Comment by nwmoriarty** [comment]
@zhengmin317 Do you have the input file for this issue?

**Comment by zhengmin317** [comment]
@nwmoriarty Please get the two pdb files before and after capping

[0_capping.pdb.zip](https://github.com/qrefine/qr-core/files/734429/0_capping.pdb.zip)
[0.pdb.zip](https://github.com/qrefine/qr-core/files/734430/0.pdb.zip)

**Comment by nwmoriarty** [comment]
Just pushed a fix and test for this issue.
