### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qr-core#32]
The run_finalise.py is split and moved into qr-core, but not all tests work.

I moved all tests for the  run_finalise.py from qr-test-cluster into qr-core since the source codes are in qr-core.

We were discussing putting large test data files out of repository qr-core.

Currently maybe  keeping source codes and test data  in one repository is more convenient to debug. Perhaps after we are confident of the source codes, large test data files can stay different place.

Also I would like to suggest: 
 if you make some changes in the source code, please make sure the related tests pass (no need to run all tests).

**Comment by pafonine** [comment]
Hi Min,

thanks for updates! A few comments:

*1)* Can we avoid creating links?

*2)* The need to have code separate from tests is two-fold:
   - qr code does not need tests to run production refinement;
   - large repository may be tricky to download in some places, like 
SHU. For example, qr-core used to be ~250KB (yes, KB, not MB!) and now 
with your recent changes it is suddenly 685MB (yes, MB, not KB 
anymore!). I suspect it's now a tricky exercise for Mark to get it in SHU.

*3)* Can we make sure tests do not output anything except "OK" and time 
taken to run? For instance, output like this

2xmt.pdb
  PDB 2xmt - charmm charge: -10, run_finalise charge: -10
2xmu.pdb
  PDB 2xmu - charmm charge: -10, run_finalise charge: -10
2y3j.pdb
  PDB 2y3j - charmm charge:  0, run_finalise charge:  0

can be replaced with

assert charmm_charge == run_finalise_charge, [pdb_code, charmm_charge, 
run_finalise_charge]

*4)* Many tests fails for me:

Running test: tst_07.py
No module named jpype
Traceback (most recent call last):
   File "tst_07.py", line 42, in <module>
     run()
   File "tst_07.py", line 19, in run
     pyoink=PYoink("../plugin/yoink/Yoink-0.0.1.jar","./cluster.xml")
   File "/Users/pafonine/qr/qr-core/tests/pyoink.py", line 16, in __init__
     startJVM(getDefaultJVMPath(), "-Djava.class.path="+yoink_jar_path)
NameError: global name 'startJVM' is not defined
Running test: tst_08.py
Sorry: No module named networkx
Running test: tst_09.py
No module named jpype
Traceback (most recent call last):
   File "tst_09.py", line 47, in <module>
     run()
   File "tst_09.py", line 33, in run
     pyoink = PYoink("../plugin/yoink/Yoink-0.0.1.jar", "./tmp_qmmm.xml")
   File "/Users/pafonine/qr/qr-core/tests/pyoink.py", line 16, in __init__
     startJVM(getDefaultJVMPath(), "-Djava.class.path="+yoink_jar_path)
NameError: global name 'startJVM' is not defined
Running test: tst_10.py
No module named jpype
No module named openbabel
Sorry: No module named terachem_qr

*5)* Running tst_11.py requires "../../qr-tests-cluster/01". I do have 
"qr-tests-cluster/01" somewhere on my computer but obviously not exactly 
here "../../qr-tests-cluster/01". So this fails for me too.

*6)* This one fails too:

babel_pdbs/clusters/13_capping.pdb babel_pdbs/capping/13_babel.pdb
atom size after babel capping: 476, after run_cluster_complete: 475
Traceback (most recent call last):
   File "tst_12.py", line 516, in <module>
     run()
   File "tst_12.py", line 503, in run
     test_capping_of_cluster_complete()
   File "tst_12.py", line 496, in test_capping_of_cluster_complete
     assert result_size ==  babel_size
AssertionError

*7)* I agree no changes should be committed before making sure all tests 
pass.

All the best,
Pavel

**Comment by zhengmin317** [comment]
Hi Pavel,

I cleaned those tests, still there are some outputs from source code.

> Running tst_11.py requires "../../qr-tests-cluster/01".
I was wondering  to get the repository from GitHub automatically and 
remove it or let the user to place it in the required place.

tst_12.py is directly from qr-test-cluster. as already mentioned, the 
test fails after the split of run_finalise.py

> *1)* Can we avoid creating links?
I am not clear about this sentence.

Min

**Comment by pafonine** [comment]
Hi Min,

> > *1)* Can we avoid creating links?
> I am not clear about this sentence.

Files like charges.py do not reside in tests. I can see them in terminal 
window, but when I use folder browser I do not see them. This is 
terribly confusing. Also, I'm not sure how this linking works on Windows 
(if works at all!). I thought we agreed last time to avoid links.


-rw-r--r--   1 pafonine  staff      0 Oct  9 20:20 __init__.py
drwxr-xr-x   4 pafonine  staff    136 Dec 29 09:01 babel_pdbs/
-rw-r--r--   1 pafonine  staff   1848 Dec 29 09:01 batch_run_finalise.py
-rw-r--r--   1 pafonine  staff   2450 Dec 29 09:07 batch_run_finalise.pyc
lrwxr-xr-x   1 pafonine  staff     13 Dec 29 09:01 charges.py@ -> 
../charges.py
-rw-r--r--   1 pafonine  staff  15228 Dec 29 09:07 charges.pyc
drwxr-xr-x  74 pafonine  staff   2516 Dec 29 09:01 charmm_pdbs/
-rw-r--r--   1 pafonine  staff  40832 Dec 29 09:07 cluster.xml
lrwxr-xr-x   1 pafonine  staff     16 Dec 29 09:01 clustering.py@ -> 
../clustering.py
-rw-r--r--   1 pafonine  staff   5204 Dec 29 09:07 clustering.pyc
lrwxr-xr-x   1 pafonine  staff     17 Dec 29 09:01 cmty.py@ -> 
../plugin/cmty.py
lrwxr-xr-x   1 pafonine  staff     16 Dec 29 09:01 completion.py@ -> 
../completion.py
etc..

Pavel

**Comment by pafonine** [comment]
Hi Min,

> > Running tst_11.py requires "../../qr-tests-cluster/01".
> I was wondering to get the repository from GitHub automatically and
> remove it or let the user to place it in the required place.

I know. It's just it does not have to be located in "../../" 
(conceptually). We don't have to solve this right now but let's think 
what may be a solution.

I think it's about time to think about directory structure and how we 
manager environment (so that we access files we need without hard-wiring 
absolute paths or creating links).

All the best,
Pavel

**Comment by nwmoriarty** [comment]
Solving this would make it much easier to maintain the Git repo. It was one of the reasons I made a mess of qr-core. I now realise how nice it is to have the automatic mechanism we have in Phenix. 👍
