### ISSUE TITLE
TeraChem dispersion correction

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qr-core#6]
1. dispersion correction does not work for many atoms.

see error below for pdb 1AKI

[error.txt](https://github.com/qrefine/qr-core/files/351991/error.txt)

**Comment by mpwaller** [comment]
I don't think it is the dispersion correction causing the problem. I would imagine that the dispersion correction is computed AFTER the energy and gradient.  It is just printing out some info about what is being used, before starting the SCF.

**Comment by zhengmin317** [comment]
Maybe @Mark you are right.

I searched it on internet, and one suggestion is to cancel dispersion 
correction.

When I set no dispersion correction, the 1AKI job ran until the 
gradients problem (Issue #7) happened.

**Comment by mpwaller** [comment]
This is a limitation of of DFT-D code used in TerraChem 1.5. It may improve with newer versions. Check the version used by TerraChem 1.9.
