### ISSUE TITLE
TeraChem gradients

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qr-core#7]
2. gradients error for  many atoms.
    see error below for pdb 1AKI

     It took ~5 hours to reach a single point calculation convergence, but failed to get the gradients

     [1aki.txt](https://github.com/qrefine/qr-core/files/351998/1aki.txt)

**Comment by mpwaller** [comment]
Perhaps you ran out of memory. If Marwin is not on the other card, try it with both?

**Comment by zhengmin317** [comment]
Another big problem is 5 hours for one single point calculation.

It's horrible.

Spending 5 hours to get energy and gradients is not worthy.

**Comment by mpwaller** [comment]
What happened with TerraChem 1.9? and could you try this on both halves of the k80?

**Comment by zhengmin317** [comment]
The latest version of cuda has not been installed yet.

**Comment by zhengmin317** [comment]
TeraChem even can not get gradients for a system with 733 atoms using one GPU cart (By the way, it took ~22 minutes to finish one single point calculation).

When it runs on two GPU carts, there is no error getting gradients.

It seems like TeraChem needs at least two GPUS for systems in medium size(~1000 atoms).

**Comment by mpwaller** [comment]
ok, thanks for the info. It looks like we need more dense GPU nodes (e.g. a server with more k80's on it).

**Comment by mpwaller** [comment]
waiting for Cuda update, then TerraChem 1.9 can be tested.

**Comment by mpwaller** [comment]
v1.9 now working, close issue.
